VENV ?= /Users/amits/code/venv
PYTHON = $(VENV)/bin/python3

run:
	$(PYTHON) calendar_agent.py

test:
	$(PYTHON) test_exchange.py

setup:
	@echo "Install cdata-exchange connector in $(VENV) (requires CData license)"
